spring:
  datasource: 
    username: hotels_final
    password: hotels_final
    url: jdbc:mysql://localhost:3306/hotels_final
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
    